version: "3.9"
services:
  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    environment:
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}

  catalog-service:
    build: ./catalog-service
    ports:
      - "3002:3002"

  reviews-service:
    build: ./reviews-service
    ports:
      - "3003:3003"

  likes-service:
    build: ./likes-service
    ports:
      - "3004:3004"
    environment:
      LIKES_PORT: ${LIKES_PORT}
      RABBITMQ_URL: ${RABBITMQ_URL}

  notification-service:
    build: ./notification-service
    ports:
      - "3005:3005"
    environment:
      NOTIFY_PORT: ${NOTIFY_PORT}
      USER_SERVICE: ${USER_SERVICE}
      GAME_SERVICE: ${GAME_SERVICE}
      REVIEW_SERVICE: ${REVIEW_SERVICE}
      RABBITMQ_URL: ${RABBITMQ_URL}
    depends_on:
      - rabbitmq

  gateway-service:
    build: ./gateway-service
    ports:
      - "8000:8000"
    environment:
      GATEWAY_PORT: ${GATEWAY_PORT}
      USER_SERVICE: ${USER_SERVICE}
      GAME_SERVICE: ${GAME_SERVICE}
      REVIEW_SERVICE: ${REVIEW_SERVICE}
      LIKES_SERVICE: ${LIKES_SERVICE}
    depends_on:
      - user-service
      - catalog-service
      - reviews-service
      - likes-service

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
